version: "2.4"

services:
  module:
    image: bverdonck/sitecore-forms-extensions-assets:${VERSION:-latest}
    build:
      context: ./module
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
    scale: 0

  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: .
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    scale: 0

  traefik:
    volumes:
      - ./docker/traefik:C:/etc/traefik
  
  mssql:
    mem_limit: 2GB
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
  
  solr:
    mem_limit: 1GB
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-cm:${VERSION:-latest}
    build:
      context: ./
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        MANAGEMENT_SERVICES_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-management-services-xm1-assets:${MANAGEMENT_SERVICES_VERSION}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
      - .\sitecorepackagedefinition:C:\inetpub\wwwroot\App_Data\packages
      - ${LOCAL_DATA_PATH}\license:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"

  id:
    volumes:
      - ${LOCAL_DATA_PATH}\license:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml

  xconnect:
    volumes:
      - ${LOCAL_DEPLOY_PATH}\xconnect:C:\deploy
      - ${LOCAL_DATA_PATH}\license:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml